version: '3'

services:
    products-loader:
        image: node:lts-slim
        environment:
            - RANDOM_SEED=1234
            - PRODUCTS_TOTAL_COUNT=999999
            - PRODUCTS_MAX_PER_REQUEST=1000
            - PRODUCT_MIN_PRICE=0.00
            - PRODUCT_MAX_PRICE=100000.00
            - MAX_CONCURRENT_REQUESTS=100
            - PORT=5555
            - NODE_ENV=debug
        working_dir: /usr/app
        volumes:
            - .:/usr/app
            - /usr/app/node_modules/
        command: [ "/bin/sh", "-c", "npm install && npm run test" ]
